FileVersion = 1
Projects = {BeefSturn = {Path = "."}, Beef-Net = {Path = "../Beef-Net"}, Beef-OpenSSL = {Path = "../Beef-Net/Beef-OpenSSL"}, BeefCrypto = {Path = "../BeefCrypto"}, BeefToml = {Path = "../Beef-Toml-trunk/lib"}}

[Workspace]
StartupProject = "BeefSturn"
